#!/bin/bash
script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "${script_dir}"

python setup.py sdist
# sdist is a source distribution
# it can be changed to binary wheel
twine upload dist/* --skip-existing
