#!/bin/bash
# Usage in Pandoctools profiles:
#   . "${python_to_PATH}" /python/root/dir
#   (${python_to_PATH} contains absolute path)
# General usage:
#   . python-to-path /python/root/dir

if [[ "$1" != "" ]]; then
    if [[ "$(uname -s)" == MINGW* ]]; then
        export PATH="$1:$1/Scripts:$1/Library/bin:$PATH"
    else
        export PATH="$1/bin:$PATH"
    fi
fi
