#!/bin/sh
# Usage in Pandoctools profiles (for Profile-Default.sh):
#   . "$import" Profile-Default

# Uses predefined absolute path variables:
#   ${_core_config} (<...>/site-packages/pandoctools/sh)
#   ${_user_config} ($HOME/.pandoc/pandoctools)

if [ -f "${_user_config}/$1.sh" ]; then
    source "${_user_config}/$1.sh"
else
    source "${_core_config}/$1.sh"
fi
