#!/bin/sh
# Imports Defaults and changes PATH
# Uses predefined variable:
#   $import
#   ${env_path} (always autocalculated by python app)
#   ${python_root_auto} (autocalculated by python app if python/envs/env_name else "")
#   ${python_root} (predefined if differs from autocalculated)

. "$import" Defaults

if [ "${python_root}" == "" ]; then
    python_root="${python_root_auto}"
fi

if [ "${python_root}" != "" ]; then
    PYTHONPATH="${python_root}"
    PATH="${python_root}/bin:$PATH"
fi
