#!/bin/bash
# Usage in Pandoctools profiles:
#   . "${python_to_PATH}" /python/root/dir
#   (${python_to_PATH} contains absolute path)
# General usage:
#   . pandoctools-python-to-path /python/root/dir

if [ "$1" != "" ]; then
    case "$(uname -s)" in
        MINGW*)
            PATH="$1:$1/Scripts:$1/Library/bin:$PATH" ;;
        *)
            PATH="$1/bin:$PATH" ;;
    esac
fi
