#!/bin/sh
# Imports CLI-Defaults and changes PATH
# ${pdt_GUI} FALSE settings work only with CLI Pandoctools usage.
# They do not change Atom package behavior.
# Uses predefined variable:
#   $import
#   ${pdt_GUI} (TRUE if in Atom package mode)
#   ${env_path} (always autocalculated by python app)
#   ${python_root_auto} (autocalculated by python app if python/envs/env_name else "")
#   ${python_root} (predefined if differs from autocalculated)

if [ "${pdt_GUI}" != "TRUE" ]; then
    . "$import" CLI-Defaults
fi

if [ "${python_root}" == "" ]; then
    python_root="${python_root_auto}"
fi

if [ "${python_root}" != "" ]; then
    PYTHONPATH="${python_root}"
    PATH="${python_root}/bin:$PATH"
fi
