#!/bin/sh
# Usage in Pandoctools profiles (for Meta-Default.yaml):
#   source "$resolve" Meta-Default.yaml

# Uses predefined absolute path variables:
#   ${core_config} (<...>/site-packages/pandoctools/sh)
#   ${user_config} ($HOME/.pandoc/pandoctools)

if [ -f "${user_config}/$1" ]; then
    echo "${user_config}/$1"
else
    echo "${core_config}/$1"
fi
