#!/bin/sh
# Simply adds conda environment to PATH.
# Uses predefined variables:
#   ${conda_env}
#   ${python_path}
#   ${env_path}

if [ "${conda_env}" != "" ]; then
    pypath="${env_path}"
    if [ "${env_path}" == "" ] && [ "${python_path}" != "" ]; then
        pypath="${python_path}/envs/${conda_env}"
    fi
    if [ "$pypath" != "" ]; then
        PATH="${pypath}/bin:$PATH"
    fi
fi
