#!/bin/sh
# Imports CLI-Defaults and changes PATH
# ${pdt_GUI} FALSE settings work only with CLI Pandoctools usage.
# They do not change Atom package behavior.
# Uses predefined variable:
#   $import
#   ${pdt_GUI} (TRUE if in Atom package mode)
#   ${conda_env} (predefined if in Atom package mode)
#   ${env_path} (predefined if in Atom package mode)
#   ${python_root} (predefined if in Atom package mode)

if [ "${pdt_GUI}" != "TRUE" ]; then
    . "$import" CLI-Defaults
fi

if [ "${python_root}" != "" ]; then
    PYTHONPATH="${python_root}"
    PATH="${python_root}/bin:$PATH"
fi
