{% set name = "pandoctools" %}
{% set version = "1.4.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 86dc08c59804d94407d41f9d9033763507cbf5a238249cb1b9f6059e3a3219a1

build:
  noarch: python
  number: 0
  entry_points:
    - cat-md = pandoctools.cat_md.cat_md:cli
    - pandoctools = pandoctools.cli.cli:pandoctools
    - pandoc-filter-arg = pandoctools.pandoc_filter_arg.cli:cli
    - pandoctools-resolve = pandoctools.pandoctools_resolve.resolve:cli
    - pandoctools-ready = pandoctools.ready.ready:ready
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pip >=10.0.1
    - setuptools
    - click
    - pyyaml
    - notebook
    - jupyter
    - panflute >=1.11.2
    - knitty >=0.4.19
    - pyppdf >=0.0.10
    - sugartex >=0.1.16
    - shortcutter >=0.1.15
    - py-pandoc-crossref
    - py-pandoc >=2.5
    - numpy
    - libsass
    - py-mathjax

test:
  imports:
    - pandoctools

about:
  home: https://github.com/kiwi0fruit/pandoctools
  license: "GPL2+"
  license_family: GPL2
  license_file: LICENSE
  summary: "Profile manager of text processing pipelines: Pandoc filters, any text CLI filters. Atom+Markdown+Pandoc+Jupyter workflow, export to ipynb."
  doc_url: https://github.com/kiwi0fruit/pandoctools
  dev_url: https://github.com/kiwi0fruit/pandoctools

extra:
  recipe-maintainers:
    - kiwi0fruit
