{% set name = "pandoctools" %}
{% set version = "2.6.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5228b2137ac009d0e9912b488d975d29b3fa01fb5751e51d596bd5cd6ca19403

build:
  noarch: python
  number: 0
  entry_points:
    - cat-md = pandoctools.cat_md.cat_md:cli
    - pandoctools = pandoctools.cli.cli:pandoctools
    - pandoctools-resolve = pandoctools.pandoctools_resolve.resolve:cli
    - pandoctools-ready = pandoctools.ready.ready:ready
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pip >=10.0.1
    - setuptools
    - click
    - pyyaml
    - notebook
    - jupyter
    - panflute >=1.11.2
    - knitty >=0.5.0
    - pyppdf >=0.0.10
    - sugartex >=0.1.16
    - shortcutter >=0.1.18
    - py-pandoc-crossref >=0.3.4.0.3
    - py-pandoc >=2.6
    - numpy
    - libsass
    - py-mathjax

test:
  imports:
    - pandoctools
    - pandoctools.ready
    - pandoctools.shared_vars
    - pandoctools.pandoctools_resolve
    - pandoctools.cli
    - pandoctools.cat_md
  commands:
    - pandoctools --help
    - pandoctools-ready
    - pandoctools-resolve Default
    - |
      echo hello | cat-md - -

about:
  home: https://github.com/kiwi0fruit/pandoctools
  license: "GPL2+"
  license_family: GPL2
  license_file: LICENSE
  summary: "Profile manager of text processing pipelines: Pandoc filters, any text CLI filters. Atom+Markdown+Pandoc+Jupyter workflow, export to ipynb."
  doc_url: https://github.com/kiwi0fruit/pandoctools
  dev_url: https://github.com/kiwi0fruit/pandoctools

extra:
  recipe-maintainers:
    - kiwi0fruit
