#!/bin/bash
# Usage:
#   . _python_to_PATH /python/root/dir

if [[ "$1" != "" ]]; then
    if [[ "$OSTYPE" == "msys" ]]; then
        PATH="$1:$1/Library/mingw-w64/bin:$1/Library/usr/bin:$1/Library/bin:$1/Scripts:$1/bin:$PATH"
    else
        PATH="$1/bin:$PATH"
    fi
fi
