#!/bin/bash
export KNITTY=True

extra_knitty=()
if [[ "${out_ext}" == "ipynb" ]]; then
    extra_knitty=("--to-ipynb"); fi

cat |
pre-knitty "${input_file}" --yaml "$metadata" |
pre-sugartex |
cat-md stdin "$metadata" "${extra_inputs[@]}" |
pandoc -f "$from2" "${reader_args[@]}" -t json |
knitty "${input_file}" -f "$from2" "${reader_args[@]}" \
    "${extra_knitty[@]}" "${writer_args2[@]}" |
panfl "${panfl_args[@]}" |
pandoc-crossref "$t" |
pandoc -f json "${writer_args2[@]}" |
if [[ "${out_ext}" == "ipynb" ]]; then
    post-knitty --to-ipynb |
    jupyter nbconvert --to notebook --execute --stdin --stdout
elif [[ "${out_ext}" == "html" ]]; then
    python -c "${replace_mathjax}" "${mathjax_url}"
else
    cat; fi
