#!/bin/bash
profile=Kiwi
md_input_only=true
source "$("$resolve" _root_env_bin_to_PATH)"
source "$("$resolve" _python_to_PATH)" "${env_path}"
source "$source" activate "${env_path}"
source "$("$resolve" ${profile}_args --else Default_args)"
panfl_args=(-t "$t" sugartex.kiwi)
source "$("$resolve" ${profile}_pipe --else Default_pipe)"
source "$source" deactivate
