#!/bin/bash
profile=NotMarkdown
md_input_only=false
if [[ "${root_env}" != "" ]]; then
    PATH="${root_env}/${scripts}:$PATH"; fi
source "$source" activate "${env_path}"
source "$("$resolve" ${profile}_args --else Default_args)"
source "$("$resolve" ${profile}_pipe --else Default_pipe)"
source "$source" deactivate
