#!/bin/bash
profile=NotMarkdown
md_input_only=false
source "$("$resolve" _root_env_bin_to_PATH)"
source "$("$resolve" _python_to_PATH)" "${env_path}"
source "$source" activate "${env_path}"
source "$("$resolve" ${profile}_args --else Default_args)"
source "$("$resolve" ${profile}_pipe --else Default_pipe)"
source "$source" deactivate
