#!/bin/bash
profile=Simple
md_input_only=false
source "$("$resolve" _env_to_PATH)" "${env_path}"
export PATH="$PATH"
source "$("$resolve" ${profile}_args --else Default_args)"
pandoc "${reader_args[@]}" "${writer_args[@]}"
